### ISSUE TITLE
Visualization of txids missing a character

### ISSUE THREAD

**Issue by dagurval** [dagurval/doublespend.cash#1]
> In Flowee I have double-spend detection as well, which is needed for some 
> other components like a point-of-sale solution build on Flowees APIs. So 
> when I noticed this in my logs today I thought I'd check if we got the same 
> data;
> 16:17:54 [2501] Double spend found 
> b86a8a170b55ebb516dd5dde036b85b4acea25a26de8e83ee0764757ec94c851 
> acb4eb8a07b6124fe14903bed92ce653081f0e0ca439a2d983154609e3fb3ceb·
> 
> I noticed that the '1' and the 'b' were missing at the end of your version 
> of events. But the clickable link has it, so its purely a minor rendering 
> issue.

(Thanks for the report @zander)

This is possibly off-by-one error in https://github.com/dagurval/doublespend.cash/blob/master/respend/websitebuilder.py#L128

@chaintip 120 days

**Comment by chaintip** [comment]
`0.01158 BCH`| `~  10.31 USD` has [been tipped](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld43lcar3cf4rtzduvtmsxlwupw3nuesw4pk2z) to this issue by @dagurval.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/29), get a pull request merged with ```@chaintip fixes #1``` in the creation comment.

**Comment by DJMcNab** [comment]
Is it possibly just the `:-1` on:
https://github.com/dagurval/doublespend.cash/blob/f7ede42db72c650d35f9faaa7db681a65a9c50f0/respend/websitebuilder.py#L130
It should be ` txid[-3:]`

See:
```python
"test"[:-1] == "tes"
```

Unless I'm mistaken, I'd say it hardly seems worth the bounty for you, to me. I'll give you this for free.

**Comment by dagurval** [comment]
Thanks @DJMcNab. I'll save it for the bounty for a new issue :-)

**Comment by chaintip** [comment]
`0 BCH`| `~   0.00 USD` has now been tipped to this issue.
To claim [this bounty](http://github.chaintip.org/chaintip/bounties/issues/29), get a pull request merged with ```@chaintip fixes #1``` in the creation comment.
